name: Run Python Tests

on:
  push:         # Run on every push to any branch
    branches: [ "master", "main" ]
  pull_request: # Run on every pull request to main/master
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository code so the workflow can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up the specified version of Python (3.10)
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Installs your project's dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Runs your pytest command!
      - name: Run tests
        run: |
          pytest